/* Check content. Reading and listening items live here because they are small,
   fixed, and need to ship with the client; the writing task comes from the API so
   it carries its board's real rubric.
   Listening audio is generated by the server's TTS module and gated by
   verifyItem() — every detail an item asks about is proven recoverable from the
   audio before a learner ever hears it. */

export const CHECK = {
  reading: {
    items: [
      {
        passage: "Immer mehr Kliniken setzen auf sogenannte Springerpools: feste Teams, die kurzfristig dort einspringen, wo Personal ausfällt. Befürworter argumentieren, dass ungeplante Überstunden dadurch deutlich zurückgehen. Kritiker wenden allerdings ein, dass die Springer selbst kaum Planungssicherheit haben.",
        q: "Was ist der Hauptkritikpunkt an Springerpools?",
        opts: [
          "Sie verursachen zusätzliche Überstunden.",
          "Die Springer haben wenig Planungssicherheit.",
          "Sie sind für die Kliniken zu teuer.",
        ],
        answer: 1,
      },
      {
        passage: "Sehr geehrte Frau Doktor Weber,\n\nwie besprochen sende ich Ihnen die Unterlagen zur Anerkennung meines Abschlusses. Leider fehlt mir noch die beglaubigte Übersetzung des Ausbildungsnachweises; diese reiche ich bis Ende des Monats nach.",
        q: "Was kündigt die schreibende Person an?",
        opts: [
          "Sie hat bereits alle Unterlagen eingereicht.",
          "Sie wird ein fehlendes Dokument bis Monatsende nachreichen.",
          "Sie bittet um eine Fristverlängerung von einem Jahr.",
        ],
        answer: 1,
      },
      {
        passage: "Die Umstellung auf die elektronische Patientenakte verläuft schleppender als geplant. Zwar sind inzwischen fast alle Häuser technisch angebunden, doch fehlt es vielerorts an Schulungen. Solange das Personal die Systeme nicht sicher bedient, bleibt der erhoffte Zeitgewinn aus.",
        q: "Woran liegt es, dass der Zeitgewinn ausbleibt?",
        opts: [
          "An fehlender technischer Anbindung.",
          "An mangelnden Schulungen für das Personal.",
          "An zu hohen Kosten der Software.",
        ],
        answer: 1,
      },
    ],
  },

  listening: {
    items: [
      {
        audio: "/b2/audio/hoeren_01.mp3",
        // Detail, not gist. Gist questions are answerable by guessing, and detail
        // is where B2 candidates actually come unstuck.
        q: "Wann wurde das Schmerzmittel zuletzt gegeben?",
        opts: ["Um 3:30 Uhr", "Um 4:30 Uhr", "Um 11:00 Uhr"],
        answer: 0,
      },
      {
        audio: "/b2/audio/hoeren_02.mp3",
        q: "Was hat sich NICHT geändert?",
        opts: ["Der Wochentag", "Die Uhrzeit", "Der Raum"],
        answer: 2,
      },
    ],
  },

  speaking: {
    prompt: "Beschreiben Sie, wie eine Übergabe auf Ihrer Station abläuft. Sprechen Sie etwa eine Minute.",
  },
};
